### ISSUE TITLE
Todo example is using getDefaultData in the store when it looks like it should be getInitialState

### ISSUE THREAD

**Issue by spoike** [spoike/refluxjs-todo#15]
From https://github.com/spoike/refluxjs/issues/136 by @ane

---

According to this merge: https://github.com/spoike/refluxjs/pull/117/files?diff=split

The connect etc. mixins now look in fetchInitialState for "getInitialState" in the store, but the example still uses the old "getDefaultData" syntax.

**Comment by aesopwolf** [comment]
@spoike is it possible to merge https://github.com/yatskevich/refluxjs-todo/commit/02d6085a3069f1f355a6316b09f399349718598c in?
