### ISSUE TITLE
Question about state

### ISSUE THREAD

**Issue by ivan-kleshnin** [spoike/refluxjs-todo#19]
I can't understand why state is duplicated throughout the system.

```
var TodoApp = React.createClass({
  // this will cause setState({list:updatedlist})...
  mixins: [Reflux.connect(todoListStore, "list")], // todo list is there

  getInitialState: function() {
    return {
      list: [] // and here yet again :(
    };
  },
```
We have "stores" which represent applilcation state, right? Yet we have this `TodoApp` object which contains the same "list" state and wires it to the state in the store. It seems like unnecessary duplication, unnecessary complexity and memory waisting. I may easily be wrong (I'm just trying to wrap my head around React), so please correct me if so. 

I currently see it like this. There are two kind of states: application (business) state and presentation state. Application state should be one "thing" (a number of stores is ok). If there's one "thing" then saving, logging, restoring application to some previous snapshot is easy. Want to roll back in history – no problem. If application state is scattered across components – we are in trouble.

If we had only components (which is possible, but is not Flux / Reflux obviously) this state would reside in top-level `AppComponent`. But as we have them, then no component should contain any "application" state at all. Props should be enough. React allows to call `setProps` on root components (or we may theoretically rerender it).

As for presentation state, it may be treated as secondary or "not yet completed" (like unsaved value in form input). It should resist in components in this architecture.

I tried to explain it generally, without references to current Reflux implementation, which I barely know at this moment.

**Comment by ivan-kleshnin** [comment]
I've finally got it. The todo-app example is slightly outdated to reflux docs. 
In **reflux** you may rely completely on store state or may add something component-specific. It makes great sense so the question is no longer valid as no enforced duplication really exists.

**Comment by spoike** [comment]
Sorry about that. I've been meaning to update the example and I have other RL priorities.

**Comment by ivan-kleshnin** [comment]
##### A note for random visitor
What I've described above just turned out to be very close to a new React dataflow architecture:
https://www.youtube.com/watch?v=9sc8Pyc51uU
Here they have one source of truth (one Store) and components accept application data through properties. There is no more Store-Application-State vs Component-Application-State dichotomy.
